name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure write permissions for the repository contents
      pages: write     # Ensure write permissions to the gh-pages branch

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js (optional, if you're using a build step like Webpack or another JS tool)
    # You can skip this if you're only using static HTML, CSS, and JS
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Change to the version you want

    # Step 3: Install dependencies (if needed)
    # - name: Install dependencies
    #   run: npm install

    # Step 4: Deploy to GitHub Pages using the `peaceiris/actions-gh-pages` action
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
        publish_dir: ./  # Directory to publish (root directory for this example)
